# Generated by Django 4.2 on 2024-10-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('quantite_eau', models.FloatField()),
                ('zone', models.CharField(max_length=255)),
            ],
        ),
    ]
